/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o código do produto");
        
        int codigoProduto = leitor.nextInt();
             
        switch(codigoProduto){
            case 1 -> System.out.println("Esse código se refere ao item Maça");
            
            case 2 -> System.out.println("Esse código se refere ao item Laranja");
                
            default -> {
            }
                
        }
    }
}
